development:
  clients:
    default:
      uri: url
#      database: zembong_development
#      hosts:
#        - localhost:27017
      options:
        server_selection_timeout: 1
#test:
#  clients:
#    default:
#      database: zembong_test
#      hosts:
#        - localhost:27017
#      options:
#        read:
#          mode: :primary
#        max_pool_size: 1
